include("$(MPY_DIR)/extmod/uasyncio")

require("dht")
require("onewire")
freeze("../../../frozen", "boot.py")
freeze("../../../frozen", "main.py")
freeze("../../../frozen", "MAX17263.mpy")
freeze("../../../frozen", "xbee.mpy")
freeze("../../../frozen", "measurements.mpy")
freeze("../../../frozen", "PRS_TruStabilitySSC.mpy")
freeze("../../../frozen", "FrameGen.mpy")
freeze("../../../frozen", "Formats.mpy")
freeze("../../../frozen", "__init__.py")