include("$(MPY_DIR)/extmod/asyncio")

require("dht")
require("onewire")
#freeze("../../../frozen", "boot.py")
#freeze("../../../frozen", "main.py")
#freeze("../../../frozen", "bmp585.py")
#freeze("../../../frozen", "i2c_helpers.py")
#freeze("../../../frozen", "MAX17263.mpy")
#freeze("../../../frozen", "xbee.mpy")
#freeze("../../../frozen", "measurements.mpy")
#freeze("../../../frozen", "FrameGen.mpy")
#freeze("../../../frozen", "Formats.mpy")
#freeze("../../../frozen", "__init__.py")
#freeze("../../../frozen", "PRS_TruStabilitySSC.mpy")
#freeze("../../../frozen", "aducm355.mpy")
#freeze("../../../frozen", "TMC7300.mpy")
#freeze("../../../frozen", "BME280.mpy")
#freeze("../../../frozen", "O2_Luminox.mpy")